In [1]:
import pandas as pd

In [2]:
cpu = pd.read_csv("../datasets/raw/CPU_benchmark_v4.csv")

In [3]:
cpu.head()

,cpuName,price,cpuMark,cpuValue,threadMark,threadValue,TDP,powerPerf,cores,testDate,socket,category
0,AMD Ryzen Threadripper PRO 5995WX,NaN,108822,NaN,3330,NaN,280.0,388.65,64,2022,sWRX8,Desktop
1,AMD EPYC 7763,7299.99,88338,12.10,2635,0.36,280.0,315.49,64,2021,SP3,Server
2,AMD EPYC 7J13,NaN,86006,NaN,2387,NaN,NaN,NaN,64,2021,unknown,Server
3,AMD EPYC 7713,7060.00,85861,12.16,2727,0.39,225.0,381.6,64,2021,SP3,Server
4,AMD Ryzen Threadripper PRO 3995WX,6807.98,83971,12.33,2626,0.39,280.0,299.9,64,2020,sWRX8,Desktop

In [4]:
cpu.shape

(3825, 12)

In [5]:
cpu.info()

<class 'pandas.DataFrame'>
RangeIndex: 3825 entries, 0 to 3824
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cpuName      3825 non-null   str
 1   price        1967 non-null   float64
 2   cpuMark      3825 non-null   int64
 3   cpuValue     1967 non-null   float64
 4   threadMark   3825 non-null   int64
 5   threadValue  1967 non-null   float64
 6   TDP          3140 non-null   float64
 7   powerPerf    3140 non-null   str
 8   cores        3825 non-null   int64
 9   testDate     3825 non-null   int64
 10  socket       3825 non-null   str
 11  category     3825 non-null   str
dtypes: float64(4), int64(4), str(4)
memory usage: 358.7 KB

In [6]:
cpu.isna().sum() #Hellnaw 1858 NaN

cpuName           0
price          1858
cpuMark           0
cpuValue       1858
threadMark        0
threadValue    1858
TDP             685
powerPerf       685
cores             0
testDate          0
socket            0
category          0
dtype: int64

In [7]:
cpu = cpu.drop(['cpuName','price','cpuValue','threadValue','powerPerf','socket'],axis=1)

In [8]:
cpu.info()

<class 'pandas.DataFrame'>
RangeIndex: 3825 entries, 0 to 3824
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cpuMark     3825 non-null   int64
 1   threadMark  3825 non-null   int64
 2   TDP         3140 non-null   float64
 3   cores       3825 non-null   int64
 4   testDate    3825 non-null   int64
 5   category    3825 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 179.4 KB

In [9]:
cpu['TDP'] = cpu['TDP'].fillna(cpu['TDP'].median())

In [10]:
cpu.info()

<class 'pandas.DataFrame'>
RangeIndex: 3825 entries, 0 to 3824
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cpuMark     3825 non-null   int64
 1   threadMark  3825 non-null   int64
 2   TDP         3825 non-null   float64
 3   cores       3825 non-null   int64
 4   testDate    3825 non-null   int64
 5   category    3825 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 179.4 KB

In [11]:
#Cleaning and Convert category into individual Boolean using get_dummies
cpu['category'] = cpu['category'].str.replace(' ','')
seperate_categories = cpu['category'].str.get_dummies(sep=',')
cpu = pd.concat([cpu,seperate_categories],axis=1)

cpu = cpu.drop('category',axis=1)

In [12]:
seperate_categories.head()

   Desktop  Laptop  Mobile/Embedded  Server  Unknown
0        1       0                0       0        0
1        0       0                0       1        0
2        0       0                0       1        0
3        0       0                0       1        0
4        1       0                0       0        0

In [13]:
cpu.head()

,cpuMark,threadMark,TDP,cores,testDate,Desktop,Laptop,Mobile/Embedded,Server,Unknown
0,108822,3330,280.0,64,2022,1,0,0,0,0
1,88338,2635,280.0,64,2021,0,0,0,1,0
2,86006,2387,53.0,64,2021,0,0,0,1,0
3,85861,2727,225.0,64,2021,0,0,0,1,0
4,83971,2626,280.0,64,2020,1,0,0,0,0

In [14]:
cpu.info()

<class 'pandas.DataFrame'>
RangeIndex: 3825 entries, 0 to 3824
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cpuMark          3825 non-null   int64
 1   threadMark       3825 non-null   int64
 2   TDP              3825 non-null   float64
 3   cores            3825 non-null   int64
 4   testDate         3825 non-null   int64
 5   Desktop          3825 non-null   int64
 6   Laptop           3825 non-null   int64
 7   Mobile/Embedded  3825 non-null   int64
 8   Server           3825 non-null   int64
 9   Unknown          3825 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 299.0 KB

In [15]:
cpu.to_csv('../datasets/processed/cpu_cleaned.csv',index=False)